# see http://about.travis-ci.org/docs/user/languages/php/ for more hints
language: php

php:
  - 4.4
  - 5.2
  - 5.3
  - 5.4
  - 5.5
  - 5.6
  - hhvm
  
script: phpunit --ignore-configuration --coverage-text
